### ISSUE TITLE
[Noetic] euslisp fails to build on armhf

### ISSUE THREAD

**Issue by sloretz** [euslisp/EusLisp#502]
Hey @k-okada,

It looks like `euslisp` isn't building on some platforms:

* [Ubuntu Focal armhf](https://build.ros.org/view/Nbin_ufhf_uFhf/job/Nbin_ufhf_uFhf__euslisp__ubuntu_focal_armhf__binary/)

I'm planning to add all chronically failing packages to per-platform blacklists later this week.
That just means the buildfarm won't try to build them every day.

When all issues causing the build failures are resolved, please make a PR to the `production` branch on [ros_buildfarm_config](https://github.com/ros-infrastructure/ros_buildfarm_config/tree/production/noetic) removing it from the `package_blacklist`:

* [release-armhf-build.yaml](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/noetic/release-armhf-build.yaml)

**Comment by k-okada** [comment]
@sloretz thanks for notification. I have fixed the probem, the same version is working on Melodic
https://build.ros.org/job/Mbin_ubhf_uBhf__euslisp__ubuntu_bionic_armhf__binary/
because Melodic contains a lot of patches https://github.com/tork-a/euslisp-release/tree/patches/release/melodic/euslisp and I just exported to Noetic https://github.com/tork-a/euslisp-release/tree/patches/release/noetic/euslisp

c.f https://github.com/ros/rosdistro/pull/37662

**Comment by k-okada** [comment]
It is working now.
![image](https://github.com/euslisp/EusLisp/assets/493276/365cb72d-23c6-4756-9dc0-fa095f1dcb1f)
